name: Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - official-fsrr-port

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release x64
        shell: pwsh
        run: msbuild OptiScaler.sln /m /p:Configuration=Release /p:Platform=x64

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: OptiScaler-FSR-RR-port
          path: |
            **/Release/**/*.dll
            **/x64/Release/**/*.dll
            OptiScaler.ini
            setup_linux.sh
            setup_windows.bat
